=begin
#AB_WebAPI

#Animation Builder Web API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::GroupsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GroupsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::GroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GroupsApi' do
    it 'should create an instact of GroupsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::GroupsApi)
    end
  end

  # unit tests for groups_get
  # Get Groups.
  # Get list of all groups.
  # @param [Hash] opts the optional parameters
  # @return [GroupDTOList]
  describe 'groups_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_group_id_delete
  # Delete Group.
  # Delete group.
  # @param group_id Id of the group to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'groups_group_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_group_id_get
  # Get Group.
  # Get group details.
  # @param group_id Id of the group to retrieve.
  # @param [Hash] opts the optional parameters
  # @return [GroupDTO]
  describe 'groups_group_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_group_id_put
  # Update Group.
  # Update group details.
  # @param group_id Id of the group to update.
  # @param group Group details containing updated group information.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'groups_group_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_group_id_sets_get
  # Get Edit Sets By Group.
  # Get edit sets of a group.
  # @param group_id Id of the group where the edit sets will be retrieved.
  # @param [Hash] opts the optional parameters
  # @return [SetDTOList]
  describe 'groups_group_id_sets_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_group_id_sets_post
  # Create Edit Set.
  # Create new edit set.
  # @param group_id Id of the group in which the edit set is created.
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'groups_group_id_sets_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
