=begin
#AB_WebAPI

#Animation Builder Web API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SetsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SetsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SetsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SetsApi' do
    it 'should create an instact of SetsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SetsApi)
    end
  end

  # unit tests for sets_get
  # Get Edit Sets.
  # Get all edit sets.
  # @param [Hash] opts the optional parameters
  # @return [SetDTOList]
  describe 'sets_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sets_set_id_delete
  # Delete Edit Set.
  # Delete edit set.
  # @param set_id The ID of the edit set to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'sets_set_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sets_set_id_get
  # Get Edit Set.
  # Get a specific edit set.
  # @param set_id The ID of the desired edit set.
  # @param [Hash] opts the optional parameters
  # @return [SetDTO]
  describe 'sets_set_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sets_set_id_put
  # Update Edit Set.
  # Update edit set.
  # @param set_id The ID of the edit set to update.
  # @param edit_set The updated edit set.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'sets_set_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
