=begin
#AB_WebAPI

#Animation Builder Web API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SettingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SettingsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsApi' do
    it 'should create an instact of SettingsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SettingsApi)
    end
  end

  # unit tests for settings_layouts_get
  # Get Local Layouts.
  # Get local layouts.
  # @param [Hash] opts the optional parameters
  # @return [VersioLayoutList]
  describe 'settings_layouts_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for settings_roots_filepicker_get
  # Get File Picker Roots.
  # Get file picker roots.
  # @param [Hash] opts the optional parameters
  # @return [RootList]
  describe 'settings_roots_filepicker_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for settings_roots_output_get
  # Get Output Roots.
  # Get render output roots.
  # @param [Hash] opts the optional parameters
  # @return [RootList]
  describe 'settings_roots_output_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for settings_versios_get
  # Get Available Versios.
  # Get available Versios.
  # @param [Hash] opts the optional parameters
  # @return [VersioList]
  describe 'settings_versios_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
